### PR TITLE
Updates README for 9.0

### PR DESCRIPTION
**Pull request by rolfkleef**
I have added a separate section for BaseX 9.0. I've tried to align it with the information on the wiki (I think the wiki could be updated a little further too).

http://docs.basex.org/wiki/Docker

### CODE REVIEW

**Comment by ChristianGruen** [comment]
Perfect, thanks a lot! If you are interested in editing our Wiki, I’ll be happy to confirm your account.

**Comment by ChristianGruen** [comment]
Quite obviously, we can do it as well; please don’t feel pressed.

**Comment by rolfkleef** [comment]
Thanks, and happy to contribute a little.

**Comment by ChristianGruen** [comment]
You should have all editing rights now.

**Pull request merged**
