### PR TITLE
Add "implements Closeable" to BaseXClient Java example to allow using…

### PR DESCRIPTION
**Pull request by vincentml**
… try-with-resources.

I've used the Java API example several times, and every time added "implements Closeable".

### CODE REVIEW

**Comment by ChristianGruen** [comment]
…makes sense, thanks.

**Comment by LeoWoerteler** [comment]
No `@Override` on `close()`?

**Comment by ChristianGruen** [comment]
See here: https://github.com/BaseXdb/basex/commit/3c57089769d907e1f573ce0f8b80bafad6c6b74f

**Comment by LeoWoerteler** [comment]
\o/

**Pull request merged**
